version: '3.5'

services:

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=false
      - node.store.allow_mmap=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataES-bootcamp:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - network-bootcamp

  kib:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
    networks:
      - network-bootcamp


volumes:
  dataES-bootcamp:
    driver: local



networks:
  network-bootcamp:
